'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings 自动保存功能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property 枚举序列() As Global.System.Collections.ArrayList
        Get
            Return CType(Me("枚举序列"),Global.System.Collections.ArrayList)
        End Get
        Set
            Me("枚举序列") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("匹配属性表")>  _
    Public Property 匹配属性表() As String
        Get
            Return CType(Me("匹配属性表"),String)
        End Get
        Set
            Me("匹配属性表") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("匹配数据表")>  _
    Public Property 匹配数据表() As String
        Get
            Return CType(Me("匹配数据表"),String)
        End Get
        Set
            Me("匹配数据表") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property 属性表1级表头行号() As Integer
        Get
            Return CType(Me("属性表1级表头行号"),Integer)
        End Get
        Set
            Me("属性表1级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 属性表2级表头行号() As Integer
        Get
            Return CType(Me("属性表2级表头行号"),Integer)
        End Get
        Set
            Me("属性表2级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 属性表3级表头行号() As Integer
        Get
            Return CType(Me("属性表3级表头行号"),Integer)
        End Get
        Set
            Me("属性表3级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property 属性表1级表头列号() As Integer
        Get
            Return CType(Me("属性表1级表头列号"),Integer)
        End Get
        Set
            Me("属性表1级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 属性表2级表头列号() As Integer
        Get
            Return CType(Me("属性表2级表头列号"),Integer)
        End Get
        Set
            Me("属性表2级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 属性表3级表头列号() As Integer
        Get
            Return CType(Me("属性表3级表头列号"),Integer)
        End Get
        Set
            Me("属性表3级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property 数据表1级表头行号() As Integer
        Get
            Return CType(Me("数据表1级表头行号"),Integer)
        End Get
        Set
            Me("数据表1级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 数据表2级表头行号() As Integer
        Get
            Return CType(Me("数据表2级表头行号"),Integer)
        End Get
        Set
            Me("数据表2级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 数据表3级表头行号() As Integer
        Get
            Return CType(Me("数据表3级表头行号"),Integer)
        End Get
        Set
            Me("数据表3级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property 数据表1级表头列号() As Integer
        Get
            Return CType(Me("数据表1级表头列号"),Integer)
        End Get
        Set
            Me("数据表1级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 数据表2级表头列号() As Integer
        Get
            Return CType(Me("数据表2级表头列号"),Integer)
        End Get
        Set
            Me("数据表2级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 数据表3级表头列号() As Integer
        Get
            Return CType(Me("数据表3级表头列号"),Integer)
        End Get
        Set
            Me("数据表3级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 数据表1级表头行名() As String
        Get
            Return CType(Me("数据表1级表头行名"),String)
        End Get
        Set
            Me("数据表1级表头行名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 数据表2级表头行名() As String
        Get
            Return CType(Me("数据表2级表头行名"),String)
        End Get
        Set
            Me("数据表2级表头行名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 数据表3级表头行名() As String
        Get
            Return CType(Me("数据表3级表头行名"),String)
        End Get
        Set
            Me("数据表3级表头行名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 数据表1级表头列名() As String
        Get
            Return CType(Me("数据表1级表头列名"),String)
        End Get
        Set
            Me("数据表1级表头列名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 数据表2级表头列名() As String
        Get
            Return CType(Me("数据表2级表头列名"),String)
        End Get
        Set
            Me("数据表2级表头列名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 数据表3级表头列名() As String
        Get
            Return CType(Me("数据表3级表头列名"),String)
        End Get
        Set
            Me("数据表3级表头列名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 属性表1级表头行名() As String
        Get
            Return CType(Me("属性表1级表头行名"),String)
        End Get
        Set
            Me("属性表1级表头行名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 属性表2级表头行名() As String
        Get
            Return CType(Me("属性表2级表头行名"),String)
        End Get
        Set
            Me("属性表2级表头行名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 属性表3级表头行名() As String
        Get
            Return CType(Me("属性表3级表头行名"),String)
        End Get
        Set
            Me("属性表3级表头行名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 属性表1级表头列名() As String
        Get
            Return CType(Me("属性表1级表头列名"),String)
        End Get
        Set
            Me("属性表1级表头列名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 属性表2级表头列名() As String
        Get
            Return CType(Me("属性表2级表头列名"),String)
        End Get
        Set
            Me("属性表2级表头列名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property 属性表3级表头列名() As String
        Get
            Return CType(Me("属性表3级表头列名"),String)
        End Get
        Set
            Me("属性表3级表头列名") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_属性表1级表头行号() As Integer
        Get
            Return CType(Me("结果页列序号_属性表1级表头行号"),Integer)
        End Get
        Set
            Me("结果页列序号_属性表1级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_属性表2级表头行号() As Integer
        Get
            Return CType(Me("结果页列序号_属性表2级表头行号"),Integer)
        End Get
        Set
            Me("结果页列序号_属性表2级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_属性表3级表头行号() As Integer
        Get
            Return CType(Me("结果页列序号_属性表3级表头行号"),Integer)
        End Get
        Set
            Me("结果页列序号_属性表3级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_属性表1级表头列号() As Integer
        Get
            Return CType(Me("结果页列序号_属性表1级表头列号"),Integer)
        End Get
        Set
            Me("结果页列序号_属性表1级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_属性表2级表头列号() As Integer
        Get
            Return CType(Me("结果页列序号_属性表2级表头列号"),Integer)
        End Get
        Set
            Me("结果页列序号_属性表2级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_属性表3级表头列号() As Integer
        Get
            Return CType(Me("结果页列序号_属性表3级表头列号"),Integer)
        End Get
        Set
            Me("结果页列序号_属性表3级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_数据表1级表头行号() As Integer
        Get
            Return CType(Me("结果页列序号_数据表1级表头行号"),Integer)
        End Get
        Set
            Me("结果页列序号_数据表1级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_数据表2级表头行号() As Integer
        Get
            Return CType(Me("结果页列序号_数据表2级表头行号"),Integer)
        End Get
        Set
            Me("结果页列序号_数据表2级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_数据表3级表头行号() As Integer
        Get
            Return CType(Me("结果页列序号_数据表3级表头行号"),Integer)
        End Get
        Set
            Me("结果页列序号_数据表3级表头行号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_数据表1级表头列号() As Integer
        Get
            Return CType(Me("结果页列序号_数据表1级表头列号"),Integer)
        End Get
        Set
            Me("结果页列序号_数据表1级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_数据表2级表头列号() As Integer
        Get
            Return CType(Me("结果页列序号_数据表2级表头列号"),Integer)
        End Get
        Set
            Me("结果页列序号_数据表2级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property 结果页列序号_数据表3级表头列号() As Integer
        Get
            Return CType(Me("结果页列序号_数据表3级表头列号"),Integer)
        End Get
        Set
            Me("结果页列序号_数据表3级表头列号") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("16620335")>  _
    Public Property 表头行背景色() As Integer
        Get
            Return CType(Me("表头行背景色"),Integer)
        End Get
        Set
            Me("表头行背景色") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("15773696")>  _
    Public Property 表头列背景色() As Integer
        Get
            Return CType(Me("表头列背景色"),Integer)
        End Get
        Set
            Me("表头列背景色") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property 循环色序列() As Global.System.Collections.ArrayList
        Get
            Return CType(Me("循环色序列"),Global.System.Collections.ArrayList)
        End Get
        Set
            Me("循环色序列") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("200000")>  _
    Public Property 醒目色() As Integer
        Get
            Return CType(Me("醒目色"),Integer)
        End Get
        Set
            Me("醒目色") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Name")>  _
    Public Property 属性表数据名称() As String
        Get
            Return CType(Me("属性表数据名称"),String)
        End Get
        Set
            Me("属性表数据名称") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Value")>  _
    Public Property 数据表数据名称() As String
        Get
            Return CType(Me("数据表数据名称"),String)
        End Get
        Set
            Me("数据表数据名称") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute(",")>  _
    Public Property 字符串分隔符() As String
        Get
            Return CType(Me("字符串分隔符"),String)
        End Get
        Set
            Me("字符串分隔符") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property 是否先行后列() As Boolean
        Get
            Return CType(Me("是否先行后列"),Boolean)
        End Get
        Set
            Me("是否先行后列") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property 是否剔除重复值() As Boolean
        Get
            Return CType(Me("是否剔除重复值"),Boolean)
        End Get
        Set
            Me("是否剔除重复值") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property 是否忽略空值() As Boolean
        Get
            Return CType(Me("是否忽略空值"),Boolean)
        End Get
        Set
            Me("是否忽略空值") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property 是否忽略首尾空白字符() As Boolean
        Get
            Return CType(Me("是否忽略首尾空白字符"),Boolean)
        End Get
        Set
            Me("是否忽略首尾空白字符") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("[空]")>  _
    Public Property 代表空值的字符串() As String
        Get
            Return CType(Me("代表空值的字符串"),String)
        End Get
        Set
            Me("代表空值的字符串") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property 是否以非空数据为边() As Boolean
        Get
            Return CType(Me("是否以非空数据为边"),Boolean)
        End Get
        Set
            Me("是否以非空数据为边") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property 是否启用任务窗格() As Boolean
        Get
            Return CType(Me("是否启用任务窗格"),Boolean)
        End Get
        Set
            Me("是否启用任务窗格") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MyExcel插件.MySettings
            Get
                Return Global.MyExcel插件.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
